// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sessionmanager/v1/session.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully-qualified username (localpart@domain or localpart+ext@domain).
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password (plaintext over the unix socket / mTLS channel).
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_sessionmanager_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionmanager_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_sessionmanager_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque session token. Include as "session-token" gRPC metadata
	// on all subsequent proxied RPCs.
	SessionToken string `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// The authenticated mailbox identifier (base@domain, subaddress stripped).
	Mailbox string `protobuf:"bytes,2,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	// Subaddress extension (e.g. "ext" from "user+ext@domain"). Empty if none.
	Extension string `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	// Per-domain sender rate limit. 0 means no domain-specific limit
	// (use the global default).
	MaxSendsPerHour int32 `protobuf:"varint,4,opt,name=max_sends_per_hour,json=maxSendsPerHour,proto3" json:"max_sends_per_hour,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_sessionmanager_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessionmanager_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_sessionmanager_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *LoginResponse) GetMailbox() string {
	if x != nil {
		return x.Mailbox
	}
	return ""
}

func (x *LoginResponse) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *LoginResponse) GetMaxSendsPerHour() int32 {
	if x != nil {
		return x.MaxSendsPerHour
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_sessionmanager_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionmanager_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_sessionmanager_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_sessionmanager_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessionmanager_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_sessionmanager_v1_session_proto_rawDescGZIP(), []int{3}
}

type ValidateRecipientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully-qualified recipient address (user@domain).
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRecipientRequest) Reset() {
	*x = ValidateRecipientRequest{}
	mi := &file_sessionmanager_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRecipientRequest) ProtoMessage() {}

func (x *ValidateRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionmanager_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRecipientRequest.ProtoReflect.Descriptor instead.
func (*ValidateRecipientRequest) Descriptor() ([]byte, []int) {
	return file_sessionmanager_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateRecipientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ValidateRecipientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if this server handles the recipient's domain.
	DomainIsLocal bool `protobuf:"varint,1,opt,name=domain_is_local,json=domainIsLocal,proto3" json:"domain_is_local,omitempty"`
	// True if the user exists in the domain. Only meaningful when
	// domain_is_local is true.
	UserExists bool `protobuf:"varint,2,opt,name=user_exists,json=userExists,proto3" json:"user_exists,omitempty"`
	// True if unknown-user rejection should be deferred to after DATA
	// (hides address validity). False means reject at RCPT TO.
	DeferRejection bool `protobuf:"varint,3,opt,name=defer_rejection,json=deferRejection,proto3" json:"defer_rejection,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateRecipientResponse) Reset() {
	*x = ValidateRecipientResponse{}
	mi := &file_sessionmanager_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRecipientResponse) ProtoMessage() {}

func (x *ValidateRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessionmanager_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRecipientResponse.ProtoReflect.Descriptor instead.
func (*ValidateRecipientResponse) Descriptor() ([]byte, []int) {
	return file_sessionmanager_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateRecipientResponse) GetDomainIsLocal() bool {
	if x != nil {
		return x.DomainIsLocal
	}
	return false
}

func (x *ValidateRecipientResponse) GetUserExists() bool {
	if x != nil {
		return x.UserExists
	}
	return false
}

func (x *ValidateRecipientResponse) GetDeferRejection() bool {
	if x != nil {
		return x.DeferRejection
	}
	return false
}

var File_sessionmanager_v1_session_proto protoreflect.FileDescriptor

const file_sessionmanager_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1fsessionmanager/v1/session.proto\x12\x11sessionmanager.v1\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x99\x01\n" +
	"\rLoginResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x18\n" +
	"\amailbox\x18\x02 \x01(\tR\amailbox\x12\x1c\n" +
	"\textension\x18\x03 \x01(\tR\textension\x12+\n" +
	"\x12max_sends_per_hour\x18\x04 \x01(\x05R\x0fmaxSendsPerHour\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\x10\n" +
	"\x0eLogoutResponse\"4\n" +
	"\x18ValidateRecipientRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x8d\x01\n" +
	"\x19ValidateRecipientResponse\x12&\n" +
	"\x0fdomain_is_local\x18\x01 \x01(\bR\rdomainIsLocal\x12\x1f\n" +
	"\vuser_exists\x18\x02 \x01(\bR\n" +
	"userExists\x12'\n" +
	"\x0fdefer_rejection\x18\x03 \x01(\bR\x0edeferRejection2\x9b\x02\n" +
	"\x0eSessionService\x12J\n" +
	"\x05Login\x12\x1f.sessionmanager.v1.LoginRequest\x1a .sessionmanager.v1.LoginResponse\x12M\n" +
	"\x06Logout\x12 .sessionmanager.v1.LogoutRequest\x1a!.sessionmanager.v1.LogoutResponse\x12n\n" +
	"\x11ValidateRecipient\x12+.sessionmanager.v1.ValidateRecipientRequest\x1a,.sessionmanager.v1.ValidateRecipientResponseB?Z=github.com/infodancer/session-manager/proto/sessionmanager/v1b\x06proto3"

var (
	file_sessionmanager_v1_session_proto_rawDescOnce sync.Once
	file_sessionmanager_v1_session_proto_rawDescData []byte
)

func file_sessionmanager_v1_session_proto_rawDescGZIP() []byte {
	file_sessionmanager_v1_session_proto_rawDescOnce.Do(func() {
		file_sessionmanager_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessionmanager_v1_session_proto_rawDesc), len(file_sessionmanager_v1_session_proto_rawDesc)))
	})
	return file_sessionmanager_v1_session_proto_rawDescData
}

var file_sessionmanager_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sessionmanager_v1_session_proto_goTypes = []any{
	(*LoginRequest)(nil),              // 0: sessionmanager.v1.LoginRequest
	(*LoginResponse)(nil),             // 1: sessionmanager.v1.LoginResponse
	(*LogoutRequest)(nil),             // 2: sessionmanager.v1.LogoutRequest
	(*LogoutResponse)(nil),            // 3: sessionmanager.v1.LogoutResponse
	(*ValidateRecipientRequest)(nil),  // 4: sessionmanager.v1.ValidateRecipientRequest
	(*ValidateRecipientResponse)(nil), // 5: sessionmanager.v1.ValidateRecipientResponse
}
var file_sessionmanager_v1_session_proto_depIdxs = []int32{
	0, // 0: sessionmanager.v1.SessionService.Login:input_type -> sessionmanager.v1.LoginRequest
	2, // 1: sessionmanager.v1.SessionService.Logout:input_type -> sessionmanager.v1.LogoutRequest
	4, // 2: sessionmanager.v1.SessionService.ValidateRecipient:input_type -> sessionmanager.v1.ValidateRecipientRequest
	1, // 3: sessionmanager.v1.SessionService.Login:output_type -> sessionmanager.v1.LoginResponse
	3, // 4: sessionmanager.v1.SessionService.Logout:output_type -> sessionmanager.v1.LogoutResponse
	5, // 5: sessionmanager.v1.SessionService.ValidateRecipient:output_type -> sessionmanager.v1.ValidateRecipientResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sessionmanager_v1_session_proto_init() }
func file_sessionmanager_v1_session_proto_init() {
	if File_sessionmanager_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessionmanager_v1_session_proto_rawDesc), len(file_sessionmanager_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessionmanager_v1_session_proto_goTypes,
		DependencyIndexes: file_sessionmanager_v1_session_proto_depIdxs,
		MessageInfos:      file_sessionmanager_v1_session_proto_msgTypes,
	}.Build()
	File_sessionmanager_v1_session_proto = out.File
	file_sessionmanager_v1_session_proto_goTypes = nil
	file_sessionmanager_v1_session_proto_depIdxs = nil
}
